### ISSUE TITLE
Validate the vector when using cosine metric

### ISSUE THREAD

**Issue by bugmakerrrrrr** [opensearch-project/k-NN#1461]
**Is your feature request related to a problem?**
When I use cosine metric and provide zero vector(all elements are zero) as query vector, I get no hits, then I realize that a zero vector is meaningless for cosine distance, but OpenSearch dose not provide any information about this, which may confuse users.

**What solution would you like?**
Validate the vector passed by the user during querying or indexing, if the vector is zero vector and the space type of index is cosine, an exception will be thrown. If you guys believe it is necessary, I can create a PR. Any thoughts? 

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by bugmakerrrrrr** [comment]
**To Reproduce**
Use data in [KNN document](https://opensearch.org/docs/latest/search-plugins/knn/filter-search-knn/#using-a-faiss-efficient-filter).
Mappings:
```
{
    "settings": {
        "index": {
            "knn": true,
            "knn.algo_param.ef_search": 100,
            "number_of_shards": 1,
            "number_of_replicas": 0
        }
    },
    "mappings": {
        "properties": {
            "item_vector": {
                "type": "knn_vector",
                "dimension": 3,
                "method": {
                    "name": "hnsw",
                    "space_type": "cosinesimil",
                    "engine": "lucene",
                    "parameters": {
                        "ef_construction": 100,
                        "m": 16
                    }
                }
            }
        }
    }
}
```
Query:
```
{
  "size": 2,
  "query": {
    "knn": {
      "item_vector": {
        "vector": [
          0, 0, 0
        ],
        "k": 10,
        "filter": {
          "bool": {
            "must": [
              {
                "range": {
                  "rating": {
                    "gte": 7,
                    "lte": 10
                  }
                }
              },
              {
                "term": {
                  "size": "small"
                }
              }
            ]
          }
        }
      }
    }
  }
}
```
This will go through exact search path, and similarity function will return a score `NaN`, then all the docs will be filter because `NEGATIVE_INFINITY`(`topDoc.score` in `HitQueue`) is not less than `NaN`.

And if we use query without filter, an exception will be thrown as follows:
```
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseFailure(AbstractSearchAsyncAction.java:665) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:373) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:704) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:473) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:295) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:104) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:74) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:755) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TransportService$6.handleException(TransportService.java:884) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1504) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1618) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1592) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:79) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:71) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:70) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.threadpool.TaskAwareRunnable.doRun(TaskAwareRunnable.java:78) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:102) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:908) [opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.9.0.jar:2.9.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.opensearch.OpenSearchException$3: Index 2147483647 out of bounds for length 12
	at org.opensearch.OpenSearchException.guessRootCauses(OpenSearchException.java:685) ~[opensearch-core-2.9.0.jar:2.9.0]
	at org.opensearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:371) [opensearch-2.9.0.jar:2.9.0]
	... 23 more
Caused by: java.lang.IndexOutOfBoundsException: Index 2147483647 out of bounds for length 12
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at org.apache.lucene.index.SegmentReader.document(SegmentReader.java:252) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
	at org.apache.lucene.index.FilterLeafReader.document(FilterLeafReader.java:404) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
	at org.apache.lucene.index.FilterLeafReader.document(FilterLeafReader.java:404) ~[lucene-core-9.7.0.jar:9.7.0 ccf4b198ec328095d45d2746189dc8ca633e8bcf - 2023-06-21 11:48:16]
	at org.opensearch.search.fetch.FetchPhase.loadStoredFields(FetchPhase.java:563) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.fetch.FetchPhase.prepareNonNestedHitContext(FetchPhase.java:337) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.fetch.FetchPhase.prepareHitContext(FetchPhase.java:298) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.fetch.FetchPhase.execute(FetchPhase.java:169) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.SearchService.executeFetchPhase(SearchService.java:628) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.SearchService.executeQueryPhase(SearchService.java:603) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:565) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:73) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.action.ActionRunnable$2.doRun(ActionRunnable.java:88) ~[opensearch-2.9.0.jar:2.9.0]
	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.9.0.jar:2.9.0]
	... 8 more
```

This is because `COSINE` similarity function will return score `NaN`, and during collecting doc using min PQ in `TopScoreDocCollector`, `NEGATIVE_INFINITY` is not less than `NaN`, so the collected doc won't be shifted down.

**Comment by bugmakerrrrrr** [comment]
When I read the Lucene source code, I also notice the documentation on VectorSimilarityFunction.DOT_PRODUCT claims that normalization is required. Therefore, it may be necessary to validate the vector when using the inner product metric.

> /**
   * Dot product. NOTE: this similarity is intended as an optimized way to perform cosine
   * similarity. In order to use it, all vectors must be normalized, including both document and
   * query vectors. Using dot product with vectors that are not normalized can result in errors or
   * poor search results. Floating point vectors must be normalized to be of unit length, while byte
   * vectors should simply all have the same norm.
   */

**Comment by jmazanec15** [comment]
I agree. We should add this validation for cosine.
