### ISSUE TITLE
[BUG] kNN create index fails on Windows 

### ISSUE THREAD

**Issue by asfoorial** [opensearch-project/k-NN#1512]
Windows 11
OS 2.12.0

Creating kNN index returns the below crashing error
PUT testindex
{"settings": {"index": {"knn": true, "knn.algo_param.ef_search": 512
    }
  }, "mappings": {"properties": {"vector_field": {"type": "knn_vector", "dimension": 384, "method": {"name": "hnsw", "space_type": "l2", "engine": "nmslib", "parameters": {"ef_construction": 512, "m": 16
          }
        }
      }
    }
  }
}

opensearch-2.12.0\plugins\opensearch-knn\lib\opensearchknn_nmslib.dll: The specified procedure could not be found
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method) ~[?:?]
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430) ~[?:?]
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487) ~[?:?]
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684) ~[?:?]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2649) ~[?:?]
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827) ~[?:?]
        at java.base/java.lang.System.loadLibrary(System.java:1871) ~[?:?]
        at org.opensearch.knn.jni.NmslibService.lambda$static$0(NmslibService.java:34) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.opensearch.knn.jni.NmslibService.<clinit>(NmslibService.java:33) ~[?:?]
        at org.opensearch.knn.jni.JNIService.createIndex(JNIService.java:36) ~[?:?]
        at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.lambda$createKNNIndexFromScratch$4(KNN80DocValuesConsumer.java:226) ~[?:?]

**Comment by jmazanec15** [comment]
Thanks @asfoorial. Was this from windows zip? i.e. did you follow: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/windows/?

**Comment by jmazanec15** [comment]
From zip, I see:
```
$ ls -la opensearch-2.12.0/plugins/opensearch-knn/lib/
total 147960
   99328 Feb 20 03:02 libgcc_s_seh-1.dll
  257024 Feb 20 03:02 libgomp-1.dll
48536473 Feb 20 03:02 libopenblas.dll
 2016256 Feb 20 03:02 libstdc++-6.dll
   53248 Feb 20 03:02 libwinpthread-1.dll
  536093 Feb 20 03:02 opensearchknn_common.dll
13431817 Feb 20 03:02 opensearchknn_faiss.dll
10810777 Feb 20 03:02 opensearchknn_nmslib.dll
```

**Comment by asfoorial** [comment]
> From zip, I see:
> 
> ```
> $ ls -la opensearch-2.12.0/plugins/opensearch-knn/lib/
> total 147960
>    99328 Feb 20 03:02 libgcc_s_seh-1.dll
>   257024 Feb 20 03:02 libgomp-1.dll
> 48536473 Feb 20 03:02 libopenblas.dll
>  2016256 Feb 20 03:02 libstdc++-6.dll
>    53248 Feb 20 03:02 libwinpthread-1.dll
>   536093 Feb 20 03:02 opensearchknn_common.dll
> 13431817 Feb 20 03:02 opensearchknn_faiss.dll
> 10810777 Feb 20 03:02 opensearchknn_nmslib.dll
> ```

Yes

**Comment by jmazanec15** [comment]
Did you mean yes to https://github.com/opensearch-project/k-NN/issues/1512#issuecomment-1981874555?

**Comment by asfoorial** [comment]
> Did you mean yes to [#1512 (comment)](https://github.com/opensearch-project/k-NN/issues/1512#issuecomment-1981874555)?

Yes 😁

**Comment by jmazanec15** [comment]
Let me check on this. Was it working on 2.11 do you know?

**Comment by jmazanec15** [comment]
For ref, this was jenkins test for windows: https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/integ-test/runs/7940/nodes/101/steps/957/log/?start=0. 

It says 
```
2024-02-20 04:10:17 INFO     | k-NN                 | with-security        | PASS  |
2024-02-20 04:10:17 INFO     | k-NN                 | without-security     | PASS  |
```

but everything does fail after k-NN which seems a little bit suspicious. cc @prudhvigodithi

**Comment by asfoorial** [comment]
Thanks.

I found the source of the issue. If I run an earlier version of OS, say 2.10.0, the the installation script adds the knn DLL libraries location to the path, when I run 2.13.0 then it appends its knn location to the PATH instead of pre-pending it. This makes it use the DLLs of 2.10.0 and thus raises the above exception.

**Comment by jmazanec15** [comment]
@asfoorial ah got it makes sense thanks. will close
