### ISSUE TITLE
[FLAKY] KNN990CodecTests testMultiFieldsKnnIndex error reproting file count

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#1828]
## Description

Getting a test failure for ` org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests`. Unable to repro locally. Its failing on the number of HNSW files that are created:
```
        // there should be 2 hnsw index files created. one for test_vector and one for my_vector
        assertEquals(hnswfiles.size(), 2);
```
Its saying that there are 4 when it expects 2. My guess is some kind of state bug that we are not accounting for.

```
 org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests > testMultiFieldsKnnIndex FAILED
    java.lang.AssertionError: expected:<4> but was:<2>
        at __randomizedtesting.SeedInfo.seed([F72B6D8EB481B0BB:4D6B7BBBDF6D89C8]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.knn.index.codec.KNNCodecTestCase.testMultiFieldsKnnIndex(KNNCodecTestCase.java:160)
        at org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testMultiFieldsKnnIndex(KNN990CodecTests.java:23)
REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testMultiFieldsKnnIndex" -Dtests.seed=F72B6D8EB481B0BB -Dtests.security.manager=false -Dtests.locale=en-JM -Dtests.timezone=America/Toronto -Druntime.java=17

  1> [2024-07-15T15:48:53,685][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testMultiFieldsKnnIndex] before test

  1> [2024-07-15T15:48:53,847][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] [testMultiFieldsKnnIndex] Refresh operation complete in 1 ms
Suite: Test class org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests
  1> [2024-07-15T15:48:53,865][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] [testMultiFieldsKnnIndex] Refresh operation complete in 2 ms
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testMultiFieldsKnnIndex" -Dtests.seed=F72B6D8EB481B0BB -Dtests.security.manager=false -Dtests.locale=en-JM -Dtests.timezone=America/Toronto -Druntime.java=17
  2> java.lang.AssertionError: expected:<4> but was:<2>
        at __randomizedtesting.SeedInfo.seed([F72B6D8EB481B0BB:4D6B7BBBDF6D89C8]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.knn.index.codec.KNNCodecTestCase.testMultiFieldsKnnIndex(KNNCodecTestCase.java:160)
        at org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testMultiFieldsKnnIndex(KNN990CodecTests.java:23)
  2> Jul 15, 2024 3:48:54 PM com.google.common.cache.LocalCache processPendingNotifications
  2> WARNING: Exception thrown by removal listener
  2> java.util.concurrent.RejectedExecutionException: Task org.opensearch.knn.index.memory.NativeMemoryAllocation$IndexAllocation$$Lambda$3987/0x0000000128b468e8@2c35933d rejected from java.util.concurrent.ThreadPoolExecutor@7f1a4fd1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
  2> 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
  2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
  2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
```

## Impacted
- #1825

**Comment by navneet1v** [comment]
@jmazanec15 do you think it happened because of any recent changes?
