### ISSUE TITLE
[Bug] Unable to create target index from model ID 

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/k-NN#1963]
### Description

Unable to create target index from a trained model on `main` branch which is failing with the below error:

```
java.lang.NoSuchFieldError: Class org.opensearch.Version does not have member field 'org.opensearch.Version V_2_17_0'
        at org.opensearch.knn.index.mapper.KNNVectorFieldMapperUtil.useLuceneKNNVectorsFormat(KNNVectorFieldMapperUtil.java:254) ~[?:?]
        at org.opensearch.knn.index.mapper.ModelFieldMapper.<init>(ModelFieldMapper.java:108) ~[?:?]
        at org.opensearch.knn.index.mapper.ModelFieldMapper.createFieldMapper(ModelFieldMapper.java:70) ~[?:?]
        at org.opensearch.knn.index.mapper.KNNVectorFieldMapper$Builder.build(KNNVectorFieldMapper.java:235) ~[?:?]
        at org.opensearch.knn.index.mapper.KNNVectorFieldMapper$Builder.build(KNNVectorFieldMapper.java:79) ~[?:?]
        at org.opensearch.index.mapper.ObjectMapper$Builder.build(ObjectMapper.java:223) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.RootObjectMapper$Builder.build(RootObjectMapper.java:112) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.DocumentMapper$Builder.<init>(DocumentMapper.java:93) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:143) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:132) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.MapperService.internalMerge(MapperService.java:478) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.index.mapper.MapperService.merge(MapperService.java:448) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.updateIndexMappingsAndBuildSortOrder(MetadataCreateIndexService.java:1318) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.lambda$applyCreateIndexWithTemporaryService$3(MetadataCreateIndexService.java:504) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.indices.IndicesService.withTempIndexService(IndicesService.java:907) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexWithTemporaryService(MetadataCreateIndexService.java:502) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequestWithV1Templates(MetadataCreateIndexService.java:643) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:464) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:471) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:377) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:67) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.MasterService.executeTasks(MasterService.java:904) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:456) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.MasterService.runTasks(MasterService.java:316) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.MasterService$Batcher.run(MasterService.java:227) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:204) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:242) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:882) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by navneet1v** [comment]
@naveentatikonda is it happening on the local? If yes then you might want to update your gradle cache.

**Comment by naveentatikonda** [comment]
> @naveentatikonda is it happening on the local? If yes then you might want to update your gradle cache.

yes, it is on my local and working fine after removing the gradle cache. Thanks!
