### ISSUE TITLE
[BUG] unable to run knn search with neural query on OS 2.16.0

### ISSUE THREAD

**Issue by IanMenendez** [opensearch-project/k-NN#1989]
**What is the bug?**
Searching with neural query brings down OS 2.16.0.

This is happening in OS 2.16.0 Image `FROM opensearchproject/opensearch:2.16.0`  but not in 2.15.0 or lower

**How to reproduce the bug?**
1. Upload and deploy ML model
2. Create index with settings knn = true and an ingest pipeline for the model
3. ingest some docs
4. Search with a neural query
5. Cluster goes down with: 
```
opensearch-node2       | fatal error in thread [opensearch[opensearch-node2][refresh][T#3]], exiting
opensearch-node2       | java.lang.UnsatisfiedLinkError: /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_common.so: /usr/share/opensearch/data/ml_cache/pytorch/1.13.1-cpu-precxx11-linux-x86_64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/opensearch/plugins/opensearch-knn/lib/libopensearchknn_util.so)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
opensearch-node2       | 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
opensearch-node2       | 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
opensearch-node2       | 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
opensearch-node2       | 	at java.base/java.lang.System.loadLibrary(System.java:2063)
opensearch-node2       | 	at org.opensearch.knn.jni.JNICommons.lambda$static$0(JNICommons.java:26)
opensearch-node2       | 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
opensearch-node2       | 	at org.opensearch.knn.jni.JNICommons.<clinit>(JNICommons.java:25)
opensearch-node2       | 	at org.opensearch.knn.index.codec.transfer.VectorTransferFloat.transfer(VectorTransferFloat.java:68)
opensearch-node2       | 	at org.opensearch.knn.index.codec.transfer.VectorTransferFloat.close(VectorTransferFloat.java:59)
opensearch-node2       | 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getPair(KNNCodecUtil.java:61)
opensearch-node2       | 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addKNNBinaryField(KNN80DocValuesConsumer.java:147)
opensearch-node2       | 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer.addBinaryField(KNN80DocValuesConsumer.java:87)
opensearch-node2       | 	at org.apache.lucene.index.BinaryDocValuesWriter.flush(BinaryDocValuesWriter.java:132)
opensearch-node2       | 	at org.apache.lucene.index.IndexingChain.writeDocValues(IndexingChain.java:424)
opensearch-node2       | 	at org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:282)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:445)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:496)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.maybeFlush(DocumentsWriter.java:450)
opensearch-node2       | 	at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:643)
opensearch-node2       | 	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:578)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:381)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:355)
opensearch-node2       | 	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:345)
opensearch-node2       | 	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
opensearch-node2       | 	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)
opensearch-node2       | 	at org.opensearch.index.engine.OpenSearchReaderManager.refreshIfNeeded(OpenSearchReaderManager.java:72)
opensearch-node2       | 	at org.opensearch.index.engine.OpenSearchReaderManager.refreshIfNeeded(OpenSearchReaderManager.java:52)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:240)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:433)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine$ExternalReaderManager.refreshIfNeeded(InternalEngine.java:413)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:167)
opensearch-node2       | 	at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:213)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine.refresh(InternalEngine.java:1865)
opensearch-node2       | 	at org.opensearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1844)
opensearch-node2       | 	at org.opensearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:4648)
opensearch-node2       | 	at org.opensearch.index.IndexService.maybeRefreshEngine(IndexService.java:1157)
opensearch-node2       | 	at org.opensearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:1301)
opensearch-node2       | 	at org.opensearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:159)
opensearch-node2       | 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:882)
opensearch-node2       | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
opensearch-node2       | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
opensearch-node2       | 	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**What is the expected behavior?**
Dont crash and perform a search

**What is your host/environment?**
Docker with `FROM opensearchproject/opensearch:2.16.0` Image

**Comment by heemin32** [comment]
Does it happen when you run knn query directly as well or it happens only when you query knn field through neural plugin?

**Comment by naveentatikonda** [comment]
This issue is coming from ml-commons through pytorch/djl. Similar issue - https://github.com/opensearch-project/ml-commons/issues/2563

@IanMenendez Can you please share the configuration and mapping details of the models and indices to replicate the issue.

@ylwu-amzn Can you please take a look into the above issue. Thanks!

**Comment by IanMenendez** [comment]
> Does it happen when you run knn query directly as well or it happens only when you query knn field through neural plugin?

Tested this and it is only happening with neural query, so I think it's better to move this to neural search or ml commons repo? can you do this?

**Comment by IanMenendez** [comment]
> This issue is coming from ml-commons through pytorch/djl. Similar issue - [opensearch-project/ml-commons#2563](https://github.com/opensearch-project/ml-commons/issues/2563)
> 
> @IanMenendez Can you please share the configuration and mapping details of the models and indices to replicate the issue.
> 
> @ylwu-amzn Can you please take a look into the above issue and confirm if it is coming from ml-commons. Thanks!

Yes, I updated the issue description

**Comment by IanMenendez** [comment]
I figured out that the issue is solved by itself if you restart the cluster. For some reason then the libraries seem to be there. 

The problem is that we use neural query in our testing pipeline and we cannot just restart a container during the testing pipeline.

**Comment by navneet1v** [comment]
> This issue is coming from ml-commons through pytorch/djl. Similar issue - [opensearch-project/ml-commons#2563](https://github.com/opensearch-project/ml-commons/issues/2563)
> 
> @IanMenendez Can you please share the configuration and mapping details of the models and indices to replicate the issue.
> 
> @ylwu-amzn Can you please take a look into the above issue and confirm if it is coming from ml-commons. Thanks!

@IanMenendez as provided by @naveentatikonda the issue seems to be coming from ML Commons. So, ideally this issue should be moved to ML Commons. But we don't have permission to transfer the issue to ML Commons. @opensearch-project/admin can you move this issue to ML Commons repo.
