### ISSUE TITLE
[IntegTest] knn.index.FaissIT.testEndToEnd_fromMethod on distribution build

### ISSUE THREAD

**Issue by peternied** [opensearch-project/k-NN#213]
While running tests on, OpenSearch-Build @805fbec on an ARM machine, `./test.sh integ-test https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/994/linux/arm64` found this failure:

Without Security - Standard Error:
```
nov 12, 2021 6:45:24 PM org.opensearch.client.RestClient logResponse
ADVERTENCIA: request [POST http://localhost:9200/_refresh?expand_wildcards=open%2Chidden] returned 1 warnings: [299 OpenSearch-1.2.0-d3101081aff62aa317c0b0334305f99f570a80ee "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"]
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod" -Dtests.seed=5862FB3C9D1D6964 -Dtests.security.manager=false -Dtests.locale=es-PA -Dtests.timezone=America/Indiana/Knox -Druntime.java=14
NOTE: leaving temporary files on disk at: /tmp/tmp3c8t73l8/k-NN/build/testrun/integTest/temp/org.opensearch.knn.index.FaissIT_5862FB3C9D1D6964-001
NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=1058, maxMBSortInHeap=5.540354048894553, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=es-PA, timezone=America/Indiana/Knox
NOTE: Linux 5.4.147-83.259.amzn2int.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=32,threads=1,free=224503960,total=536870912
NOTE: All tests run in this JVM: [RestLegacyKNNStatsHandlerIT, FaissIT]
```
Without Security - Test Failure:
```
testEndToEnd_fromMethod
java.lang.AssertionError: expected:<4.2039558144E11> but was:<4.20395614208E11>
	at __randomizedtesting.SeedInfo.seed([5862FB3C9D1D6964:B2B29E57E7A6649F]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod(FaissIT.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

With Security - Standard Error
```
WARNING: request [DELETE https://localhost:9200/_index_template/*] returned 1 warnings: [299 OpenSearch-1.2.0-d3101081aff62aa317c0b0334305f99f570a80ee "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"]
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod" -Dtests.seed=D0D5CDBB25E7B89 -Dtests.security.manager=false -Dtests.locale=is-IS -Dtests.timezone=PNT -Druntime.java=14
NOTE: leaving temporary files on disk at: /tmp/tmp3c8t73l8/k-NN/build/testrun/integTest/temp/org.opensearch.knn.index.FaissIT_D0D5CDBB25E7B89-001
NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=975, maxMBSortInHeap=7.488052457020542, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=is-IS, timezone=PNT
NOTE: Linux 5.4.147-83.259.amzn2int.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=32,threads=1,free=465038656,total=536870912
NOTE: All tests run in this JVM: [RestLegacyKNNStatsHandlerIT, RestSearchModelHandlerIT, RestKNNStatsHandlerIT, RestGetModelHandlerIT, RestKNNWarmupHandlerIT, RestDeleteModelHandlerIT, RestTrainModelHandlerIT, RestLegacyKNNWarmupHandlerIT, KNNScriptScoringIT, PainlessScriptScoringIT, KNNCircuitBreakerIT, KNNESSettingsTestIT, FaissIT]
```

With Security - Test Failure:
```
testEndToEnd_fromMethod
java.lang.AssertionError: expected:<4.2039558144E11> but was:<4.20395614208E11>
	at __randomizedtesting.SeedInfo.seed([D0D5CDBB25E7B89:E7DD39B0C8E57672]:0)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod(FaissIT.java:118)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by VijayanB** [comment]
@peternied changes are merged in 1.2 branch. Please update if this error is fixed.

**Comment by peternied** [comment]
@VijayanB Has this change been backported into 1.2?

**Comment by naveentatikonda** [comment]
@peternied It is backported to 1.2
https://github.com/opensearch-project/k-NN/pull/219

**Comment by peternied** [comment]
Started the test with build `1060`, will update when it has completed

**Comment by peternied** [comment]
Yes it is resolved.
