### ISSUE TITLE
[IntegTest] knn.plugin.action.RestLegacyKNNStatsHandlerIT on distribution build

### ISSUE THREAD

**Issue by peternied** [opensearch-project/k-NN#214]
While running tests on, OpenSearch-Build @805fbec on an ARM machine, `./test.sh integ-test https://ci.opensearch.org/ci/dbc/bundle-build/1.2.0/994/linux/arm64` found this failure:

With Security - Standard Error
```
WARNING: request [DELETE https://localhost:9200/_data_stream/*] returned 1 warnings: [299 OpenSearch-1.2.0-d3101081aff62aa317c0b0334305f99f570a80ee "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"]
نوف 12, 2021 2:40:35 م org.opensearch.client.RestClient logResponse
WARNING: request [DELETE https://localhost:9200/_index_template/*] returned 1 warnings: [299 OpenSearch-1.2.0-d3101081aff62aa317c0b0334305f99f570a80ee "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"]
NOTE: leaving temporary files on disk at: /tmp/tmp3c8t73l8/k-NN/build/testrun/integTest/temp/org.opensearch.knn.plugin.action.RestLegacyKNNStatsHandlerIT_D0D5CDBB25E7B89-001
NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=830, maxMBSortInHeap=7.832862973188169, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=ar-QA, timezone=US/Aleutian
NOTE: Linux 5.4.147-83.259.amzn2int.aarch64 aarch64/AdoptOpenJDK 14.0.2 (64-bit)/cpus=32,threads=1,free=398263400,total=536870912
NOTE: All tests run in this JVM: [RestLegacyKNNStatsHandlerIT]
```

With Security - Test Failure:
```
testStatsValueCheck
org.opensearch.client.ResponseException: method [DELETE], host [https://localhost:9200], URI [/.ds-test-data-stream-000001], status line [HTTP/1.1 400 Bad Request]
Warnings: [this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"index [.ds-test-data-stream-000001] is the write index for data stream [test-data-stream] and cannot be deleted"}],"type":"illegal_argument_exception","reason":"index [.ds-test-data-stream-000001] is the write index for data stream [test-data-stream] and cannot be deleted"},"status":400}
	at __randomizedtesting.SeedInfo.seed([D0D5CDBB25E7B89:FE63EF589923DE1D]:0)
	at org.opensearch.client.RestClient.convertResponse(RestClient.java:344)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:314)
	at org.opensearch.client.RestClient.performRequest(RestClient.java:289)
	at org.opensearch.knn.ODFERestTestCase.wipeAllODFEIndices(ODFERestTestCase.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by jmazanec15** [comment]
@peternied  Is this not failing for any of the other plugins?

**Comment by peternied** [comment]
Not failing for any others

**Comment by jmazanec15** [comment]
It appears that it is only failing on k-NN on arm because k-NN does not use an admin client to perform deletion. Only happening on ARM is probably due to some test ordering issue. I think the fix will be pretty simple: just [follow AD](https://github.com/opensearch-project/anomaly-detection/blob/main/src/test/java/org/opensearch/ad/ODFERestTestCase.java#L93).
