### ISSUE TITLE
[BUG] Fix a flaky test in `KNN990CodecTests::testBuildFromModelTemplate`. It is failing to get a mocking value.

### ISSUE THREAD

**Issue by 0ctopus13prime** [opensearch-project/k-NN#2257]
**What is the bug?**
`KNN990CodecTests::testBuildFromModelTemplate` does a static mocking to return a mocked `OpenSearchKNNModelDao` where it suppose to return a predefined value `ModelMetadata`, but the actual value returned is either null or its state does not equal to `ModelState.CREATED`.

```
        try (MockedStatic<ModelDao.OpenSearchKNNModelDao> modelDaoMockedStatic = Mockito.mockStatic(ModelDao.OpenSearchKNNModelDao.class)) {
            ModelDao.OpenSearchKNNModelDao modelDao = mock(ModelDao.OpenSearchKNNModelDao.class);
            modelDaoMockedStatic.when(ModelDao.OpenSearchKNNModelDao::getInstance).thenReturn(modelDao);
...


            ModelMetadata modelMetadata1 = new ModelMetadata(
                knnEngine,
                spaceType,
                dimension,
                ModelState.CREATED, <------------- It's state is CREATED

...


            Model mockModel = new Model(modelMetadata1, modelBlob, modelId);
            when(modelDao.get(modelId)).thenReturn(mockModel);
            when(modelDao.getMetadata(modelId)).thenReturn(modelMetadata1); <------ It should return the mocked state.
```

However, it keeps getting false from `isModelCreated(modelMetadata)`.

```
  1> java.lang.IllegalArgumentException: Model ID 'test-model' is not created.
  1> 	at org.opensearch.knn.indices.ModelUtil.getModelMetadata(ModelUtil.java:54)
  1> 	at org.opensearch.knn.common.FieldInfoExtractor.extractKNNEngine(FieldInfoExtractor.java:42)
  1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeKNNEngine(KNNCodecUtil.java:126)
  1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeEngineFileFromFieldInfo(KNNCodecUtil.java:106)
```

**How can one reproduce the bug?**
It's tricky to reproduce it, sometimes when we're lucky we can see the failure, but mostly it will pass. Very subtle.

**What is the expected behavior?**
We should be able to get `modelMetadata1` when `modelDao.getMetadata("test-model")` was called.
But somehow an invalid value is being return. There are two possible cases.
1. `null` : false will be returned as a result of evaluation of `modelMetadata != null`
2. It's state was not `ModelState.CREATED`. False == `return modelMetadata.getState().equals(ModelState.CREATED)`.

```
    public static boolean isModelPresent(ModelMetadata modelMetadata) {
        return modelMetadata != null;
    }

    public static boolean isModelCreated(ModelMetadata modelMetadata) {
        if (!isModelPresent(modelMetadata)) {
            return false;
        }
        return modelMetadata.getState().equals(ModelState.CREATED);
    }
```

**What is your host/environment?**
 - OS: Windows
 - Version : 2.x branch
 - Plugins : KNN

**Do you have any screenshots?**
Error logs:
```
  2> java.lang.RuntimeException: CheckIndex failed
        at __randomizedtesting.SeedInfo.seed([C26A40CD175601BB:4B1A74C7DA1BEBB9]:0)
        at org.apache.lucene.tests.util.TestUtil.checkIndex(TestUtil.java:350)
        at org.apache.lucene.tests.util.TestUtil.checkIndex(TestUtil.java:316)
        at org.apache.lucene.tests.store.BaseDirectoryWrapper.close(BaseDirectoryWrapper.java:44)
        at org.opensearch.knn.index.codec.KNNCodecTestCase.testBuildFromModelTemplate(KNNCodecTestCase.java:311)
        at org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testBuildFromModelTemplate(KNN990CodecTests.java:28)
  2> NOTE: leaving temporary files on disk at: D:\a\k-NN\k-NN\build\testrun\test\temp\org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests_C26A40CD175601BB-001
  2> NOTE: test params are: codec=Asserting(Lucene912): {}, docValues:{}, maxPointsInLeafNode=431, maxMBSortInHeap=7.043039621004881, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=be, timezone=America/Merida
  2> NOTE: Windows Server 2022 10.0 amd64/Azul Systems, Inc. 21.0.5 (64-bit)/cpus=4,threads=1,free=219468992,total=536870912
  2> NOTE: All tests run in this JVM: [FieldInfoExtractorTests, KNNVectorUtilTests, OutOfNativeMemoryExceptionTests, KNNCreateIndexFromModelTests, KNNSettingsTests, KNNVectorIndexFieldDataTests, SpaceTypeTests, VectorQueryTypeTests, KNNCodecServiceTests, KNN80CompoundFormatTests, KNN80DocValuesProducerTests, KNN990CodecTests]
  1> [2024-11-05T14:33:11,291][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testMultiFieldsKnnIndex] after test
  1> [2024-11-05T14:33:11,307][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testBuildFromModelTemplate] before test
  1> [2024-11-05T14:33:11,463][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] [testBuildFromModelTemplate] Refresh operation complete in 2 ms
  1> CheckIndex failed
  1> Checking index with threadCount: 5
  1> 0.00% total deletions; 4 documents; 0 deletions
  1> Segments file=segments_1 numSegments=1 version=9.12.0 id=838s7v3r6oozl7y19i1ybh8c2
  1> 1 of 1: name=_0 maxDoc=4
  1>     version=9.12.0
  1>     id=838s7v3r6oozl7y19i1ybh8bz
  1>     codec=KNN990Codec
  1>     compound=true
  1>     numFiles=4
  1>     size (MB)=0.002
  1>     diagnostics = {os.version=10.0, os.arch=amd64, java.vendor=Azul Systems, Inc., os=Windows Server 2022, java.runtime.version=21.0.5+11-LTS, timestamp=1730838791463, source=flush, lucene.version=9.12.0}
  1>     no deletions
  1>     test: open reader.........FAILED
  1>     WARNING: exorciseIndex() would remove reference to this segment; full exception:
  1> java.lang.IllegalArgumentException: Model ID 'test-model' is not created.
  1> 	at org.opensearch.knn.indices.ModelUtil.getModelMetadata(ModelUtil.java:54)
  1> 	at org.opensearch.knn.common.FieldInfoExtractor.extractKNNEngine(FieldInfoExtractor.java:42)
  1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeKNNEngine(KNNCodecUtil.java:126)
  1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeEngineFileFromFieldInfo(KNNCodecUtil.java:106)
  1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesProducer.getVectorCacheKeysFromSegmentReaderState(KNN80DocValuesProducer.java:97)
  1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesProducer.<init>(KNN80DocValuesProducer.java:41)
  1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesFormat.fieldsProducer(KNN80DocValuesFormat.java:44)
  1> 	at org.apache.lucene.index.SegmentDocValues.newDocValuesProducer(SegmentDocValues.java:52)
  1> 	at org.apache.lucene.index.SegmentDocValues.getDocValuesProducer(SegmentDocValues.java:69)
  1> 	at org.apache.lucene.index.SegmentReader.initDocValuesProducer(SegmentReader.java:197)
  1> 	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:113)
  1> 	at org.apache.lucene.index.CheckIndex.testSegment(CheckIndex.java:1015)
  1> 	at org.apache.lucene.index.CheckIndex.lambda$checkIndex$1(CheckIndex.java:854)
  1> 	at org.apache.lucene.index.CheckIndex.lambda$callableToSupplier$2(CheckIndex.java:954)
  1> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  1> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  1> 	at java.base/java.lang.Thread.run(Thread.java:1583)
  1>
  1>
  1> WARNING: 1 broken segments (containing 4 documents) detected
  1> Took 0.005 sec total.
  1>
  1> [2024-11-05T14:33:11,479][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testBuildFromModelTemplate] after test
  1> [2024-11-05T14:33:11,510][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testCodecSetsCustomPerFieldKnnVectorsFormat] before test
  1> [2024-11-05T14:33:11,510][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testCodecSetsCustomPerFieldKnnVectorsFormat] after test
  1> [2024-11-05T14:33:11,526][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testKnnVectorIndex] before test
  1> [2024-11-05T14:33:11,766][INFO ][o.o.k.i.c.K.KNN990CodecTests] [testKnnVectorIndex] after test
WARNING clustering 100 points to 5 centroids: please provide at least 195 training points



> Task :test
927 tests completed, 1 failed, 2 skipped

Tests with failures:
 - org.opensearch.knn.index.codec.KNN990Codec.KNN990CodecTests.testBuildFromModelTemplate

> Task :test FAILED


Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///D:/a/k-NN/k-NN/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 41m 31s

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
76 actionable tasks: 76 executed
Error: Process completed with exit code 1.
```

**Do you have any additional context?**
N/A

**Comment by finnroblin** [comment]
Also (very rarely) failing in KNN10010CodecTests: CI failed [here](https://github.com/opensearch-project/k-NN/actions/runs/15400151372/job/43330562555?pr=2718). Offending seed: 4AC30CF07F92C845, OS: macos JDK 23.
./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN10010Codec.KNN10010CodecTests.testBuildFromModelTemplate" -Dtests.seed=4AC30CF07F92C845 -Dtests.security.manager=false -Dtests.locale=nqo-Nkoo-GN -Dtests.timezone=Asia/Colombo -Druntime.java=23

Copy of error logs:
```
2025-06-02T19:43:42.4295270Z Suite: Test class org.opensearch.knn.index.codec.KNN10010Codec.KNN10010CodecTests
2025-06-02T19:43:42.4297130Z   1> [2025-06-03T01:13:41,550][INFO ][o.o.k.i.c.K.KNN10010CodecTests] [testKnnVectorIndex] after test
2025-06-02T19:43:42.4299400Z   1> [2025-06-03T01:13:41,563][INFO ][o.o.k.i.c.K.KNN10010CodecTests] [testBuildFromModelTemplate] before test
2025-06-02T19:43:42.4301680Z   1> [2025-06-03T01:13:41,788][WARN ][o.o.k.i.c.K.KNN80DocValuesConsumer] [testBuildFromModelTemplate] Refresh operation complete in 8 ms
2025-06-02T19:43:42.4459060Z   2> ߥߊ߬ߛ ߀߃, ߂߀߂߅ ߁:߁߃:߄߁ ߛ com.google.common.cache.LocalCache processPendingNotifications
2025-06-02T19:43:42.4460640Z   2> WARNING: Exception thrown by removal listener
2025-06-02T19:43:42.4461680Z   1> CheckIndex failed
2025-06-02T19:43:42.4462340Z   1> Checking index with threadCount: 2
2025-06-02T19:43:42.4462970Z   1> 0.00% total deletions; 4 documents; 0 deletions
2025-06-02T19:43:42.4464670Z   1> Segments file=segments_1 numSegments=1 version=10.2.1 id=6gx6e5mt2f50xe6kqw33tcvsh
2025-06-02T19:43:42.4465600Z   1> 1 of 1: name=_0 maxDoc=4
2025-06-02T19:43:42.4466080Z   1>     version=10.2.1
2025-06-02T19:43:42.4466870Z   1>     id=6gx6e5mt2f50xe6kqw33tcvse
2025-06-02T19:43:42.4467540Z   1>     codec=KNN10010Codec
2025-06-02T19:43:42.4468000Z   1>     compound=false
2025-06-02T19:43:42.4468870Z   1>     numFiles=8
2025-06-02T19:43:42.4469420Z   1>     size (MB)=0.001
2025-06-02T19:43:42.4471150Z   1>     diagnostics = {java.vendor=Eclipse Adoptium, os=Mac OS X, java.runtime.version=23.0.2+7, timestamp=1748893421795, source=flush, lucene.version=10.2.1, os.version=13.7.6, os.arch=x86_64}
2025-06-02T19:43:42.4473290Z   1>     no deletions
2025-06-02T19:43:42.4474850Z   1>     test: open reader.........FAILED
2025-06-02T19:43:42.4475570Z   1>     WARNING: exorciseIndex() would remove reference to this segment; full exception:
2025-06-02T19:43:42.4476840Z   1> java.lang.IllegalArgumentException: Model ID 'test-model' is not created.
2025-06-02T19:43:42.4478030Z   1> 	at org.opensearch.knn.indices.ModelUtil.getModelMetadata(ModelUtil.java:54)
2025-06-02T19:43:42.4479190Z   1> 	at org.opensearch.knn.common.FieldInfoExtractor.extractKNNEngine(FieldInfoExtractor.java:44)
2025-06-02T19:43:42.4480640Z   1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeKNNEngine(KNNCodecUtil.java:154)
2025-06-02T19:43:42.4482390Z   1> 	at org.opensearch.knn.index.codec.util.KNNCodecUtil.getNativeEngineFileFromFieldInfo(KNNCodecUtil.java:109)
2025-06-02T19:43:42.4485580Z   1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesProducer.getVectorCacheKeysFromSegmentReaderState(KNN80DocValuesProducer.java:102)
2025-06-02T19:43:42.4488250Z   1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesProducer.<init>(KNN80DocValuesProducer.java:34)
2025-06-02T19:43:42.4489950Z   1> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesFormat.fieldsProducer(KNN80DocValuesFormat.java:44)
2025-06-02T19:43:42.4491890Z   1> 	at org.apache.lucene.index.SegmentDocValues.newDocValuesProducer(SegmentDocValues.java:51)
2025-06-02T19:43:42.4493810Z   1> 	at org.apache.lucene.index.SegmentDocValues.getDocValuesProducer(SegmentDocValues.java:68)
2025-06-02T19:43:42.4495140Z   1> 	at org.apache.lucene.index.SegmentReader.initDocValuesProducer(SegmentReader.java:196)
2025-06-02T19:43:42.4496510Z   1> 	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:112)
2025-06-02T19:43:42.4498270Z   1> 	at org.apache.lucene.index.CheckIndex.testSegment(CheckIndex.java:1001)
2025-06-02T19:43:42.4499510Z   1> 	at org.apache.lucene.index.CheckIndex.lambda$checkIndex$2(CheckIndex.java:840)
2025-06-02T19:43:42.4501030Z   1> 	at org.apache.lucene.index.CheckIndex.lambda$callableToSupplier$3(CheckIndex.java:940)
2025-06-02T19:43:42.4503230Z   1> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1812)
2025-06-02T19:43:42.4505250Z   1> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2025-06-02T19:43:42.4508740Z   2> java.util.concurrent.RejectedExecutionException: Task org.opensearch.knn.index.memory.NativeMemoryAllocation$IndexAllocation$$Lambda/0x000000078cd0bcf8@1e74c4e3 rejected from java.util.concurrent.ThreadPoolExecutor@1fd8df86[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2025-06-02T19:43:42.4511900Z   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
2025-06-02T19:43:42.4513560Z   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
2025-06-02T19:43:42.4514860Z   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
2025-06-02T19:43:42.4516410Z   2> 	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:754)
2025-06-02T19:43:42.4518880Z   2> 	at org.opensearch.knn.index.memory.NativeMemoryAllocation$IndexAllocation.closeInternal(NativeMemoryAllocation.java:195)
2025-06-02T19:43:42.4520940Z   2> 	at org.opensearch.common.concurrent.RefCountedReleasable.closeInternal(RefCountedReleasable.java:49)
2025-06-02T19:43:42.4522800Z   2> 	at org.opensearch.common.util.concurrent.AbstractRefCounted.decRef(AbstractRefCounted.java:78)
2025-06-02T19:43:42.4524890Z   2> 	at org.opensearch.common.concurrent.RefCountedReleasable.close(RefCountedReleasable.java:39)
2025-06-02T19:43:42.4526570Z   2> 	at org.opensearch.knn.index.memory.NativeMemoryAllocation$IndexAllocation.close(NativeMemoryAllocation.java:202)
2025-06-02T19:43:42.4528480Z   2> 	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.onRemoval(NativeMemoryCacheManager.java:528)
2025-06-02T19:43:42.4530600Z   2> 	at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1851)
2025-06-02T19:43:42.4531780Z   2> 	at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3508)
2025-06-02T19:43:42.4533120Z   2> 	at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3484)
2025-06-02T19:43:42.4534790Z   2> 	at com.google.common.cache.LocalCache$Segment.remove(LocalCache.java:3113)
2025-06-02T19:43:42.4535730Z   2> 	at com.google.common.cache.LocalCache.remove(LocalCache.java:4316)
2025-06-02T19:43:42.4536760Z   2> 	at com.google.common.cache.LocalCache$LocalManualCache.invalidate(LocalCache.java:4961)
2025-06-02T19:43:42.4539120Z   2> 	at org.opensearch.knn.index.memory.NativeMemoryCacheManager.invalidate(NativeMemoryCacheManager.java:473)
2025-06-02T19:43:42.4541460Z   2> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
2025-06-02T19:43:42.4543350Z   2> 	at org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesProducer.close(KNN80DocValuesProducer.java:82)
2025-06-02T19:43:42.4544810Z   2> 	at org.apache.lucene.index.SegmentDocValues$1.release(SegmentDocValues.java:55)
2025-06-02T19:43:42.4546320Z   2> 	at org.apache.lucene.util.RefCount.decRef(RefCount.java:51)
2025-06-02T19:43:42.4547580Z   2> 	at org.apache.lucene.index.SegmentDocValues.lambda$decRef$0(SegmentDocValues.java:84)
2025-06-02T19:43:42.4548800Z   2> 	at org.apache.lucene.util.IOUtils.lambda$applyToAll$0(IOUtils.java:467)
2025-06-02T19:43:42.4549610Z   2> 	at org.apache.lucene.util.IOUtils.close(IOUtils.java:85)
2025-06-02T19:43:42.4550340Z   2> 	at org.apache.lucene.util.IOUtils.applyToAll(IOUtils.java:466)
2025-06-02T19:43:42.4551720Z   2> 	at org.apache.lucene.index.SegmentDocValues.decRef(SegmentDocValues.java:79)
2025-06-02T19:43:42.4552940Z   2> 	at org.apache.lucene.index.SegmentReader.doClose(SegmentReader.java:228)
2025-06-02T19:43:42.4554150Z   2> 	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:258)
2025-06-02T19:43:42.4555370Z   2> 	at org.apache.lucene.util.IOUtils.lambda$applyToAll$0(IOUtils.java:467)
2025-06-02T19:43:42.4556630Z   2> 	at org.apache.lucene.util.IOUtils.close(IOUtils.java:85)
2025-06-02T19:43:42.4557660Z   2> 	at org.apache.lucene.util.IOUtils.applyToAll(IOUtils.java:466)
2025-06-02T19:43:42.4559010Z   2> 	at org.apache.lucene.index.StandardDirectoryReader.doClose(StandardDirectoryReader.java:482)
2025-06-02T19:43:42.4560110Z   2> 	at org.apache.lucene.index.IndexReader.decRef(IndexReader.java:258)
2025-06-02T19:43:42.4561260Z   2> 	at org.apache.lucene.index.IndexReader.close(IndexReader.java:385)
2025-06-02T19:43:42.4563070Z   2> 	at org.opensearch.knn.index.codec.KNNCodecTestCase.testBuildFromModelTemplate(KNNCodecTestCase.java:310)
2025-06-02T19:43:42.4564770Z   2> 	at org.opensearch.knn.index.codec.KNN10010Codec.KNN10010CodecTests.testBuildFromModelTemplate(KNN10010CodecTests.java:28)
2025-06-02T19:43:42.4566830Z   2> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2025-06-02T19:43:42.4568390Z   2> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2025-06-02T19:43:42.4569520Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
2025-06-02T19:43:42.4570800Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
2025-06-02T19:43:42.4572570Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
2025-06-02T19:43:42.4574140Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
2025-06-02T19:43:42.4575510Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4576540Z   2> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2025-06-02T19:43:42.4577670Z   2> 	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
2025-06-02T19:43:42.4579150Z   2> 	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
2025-06-02T19:43:42.4581210Z   2> 	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
2025-06-02T19:43:42.4582760Z   2> 	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
2025-06-02T19:43:42.4584190Z   2> 	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
2025-06-02T19:43:42.4585140Z   2> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2025-06-02T19:43:42.4586160Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4587610Z   2> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
2025-06-02T19:43:42.4589820Z   2> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
2025-06-02T19:43:42.4591300Z   2> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
2025-06-02T19:43:42.4592660Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
2025-06-02T19:43:42.4594940Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
2025-06-02T19:43:42.4596250Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
2025-06-02T19:43:42.4597550Z   2> 	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
2025-06-02T19:43:42.4599260Z   2> 	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
2025-06-02T19:43:42.4600680Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4602040Z   2> 	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
2025-06-02T19:43:42.4603800Z   2> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
2025-06-02T19:43:42.4605960Z   2> 	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
2025-06-02T19:43:42.4608030Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4609800Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4611740Z   2> 	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
2025-06-02T19:43:42.4613530Z   2> 	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
2025-06-02T19:43:42.4615130Z   2> 	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
2025-06-02T19:43:42.4616600Z   2> 	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
2025-06-02T19:43:42.4618130Z   2> 	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
2025-06-02T19:43:42.4619190Z   2> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
2025-06-02T19:43:42.4620200Z   2> 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
2025-06-02T19:43:42.4621650Z   2> 	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
2025-06-02T19:43:42.4623250Z   2> 	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-06-02T19:43:42.4623900Z 
2025-06-02T19:43:42.4626050Z   2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.knn.index.codec.KNN10010Codec.KNN10010CodecTests.testBuildFromModelTemplate" -Dtests.seed=4AC30CF07F92C845 -Dtests.security.manager=false -Dtests.locale=nqo-Nkoo-GN -Dtests.timezone=Asia/Colombo -Druntime.java=23
```

**Comment by mahaponraj** [comment]
Hi, interested to solve this issue

**Comment by arshiyasharma** [comment]
Hi, Could you assign this issue to me?
I'm a student in the CodePath AI301 program and I'd like to work on this issue. I'll start by reproducing the problem locally this week. Any pointers on where to start in the codebase would be appreciated!

**Comment by AzazelSensei** [comment]
Opened https://github.com/opensearch-project/k-NN/pull/3553 for this.
