### ISSUE TITLE
[Flaky Unit test failure][WIndows]  UpdateModelGraveyardTransportActionTests fails in CI

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/k-NN#2358]
**What is the bug?**
Flaky test Failure causing CI to fail

**How can one reproduce the bug?**
```
REPRODUCE WITH: gradlew ':test' --tests "org.opensearch.knn.plugin.transport.UpdateModelGraveyardTransportActionTests.testClusterManagerOperation_GetIndicesUsingModel" -Dtests.seed=926B1157A53D5556 -Dtests.security.manager=false -Dtests.locale=en-150 -Dtests.timezone=Pacific/Auckland -Druntime.java=21
```

**What is the expected behavior?**
No test failure

**What is your host/environment?**
 - OS: Windows
 - Version 2.X

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
Error Message:
```
org.opensearch.knn.plugin.transport.UpdateModelGraveyardTransportActionTests > testClusterManagerOperation_GetIndicesUsingModel FAILED
    java.lang.AssertionError: Failed to add model: [.opensearch-knn-models/AclqSkbqRUSkMeGdq_f09w] IndexNotFoundException[no such index [.opensearch-knn-models]]
        at __randomizedtesting.SeedInfo.seed([926B1157A53D5556]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.opensearch.knn.KNNSingleNodeTestCase$1.onFailure(KNNSingleNodeTestCase.java:275)
        at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90)
        at org.opensearch.core.action.ActionListener$1.onFailure(ActionListener.java:90)
        at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:124)
        at org.opensearch.action.bulk.TransportSingleItemBulkWriteAction.lambda$wrapBulkResponse$0(TransportSingleItemBulkWriteAction.java:86)
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82)
        at org.opensearch.core.action.ActionListener$6.onResponse(ActionListener.java:301)
        at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.finishHim(TransportBulkAction.java:701)
        at org.opensearch.action.bulk.TransportBulkAction$BulkOperation$1.onFailure(TransportBulkAction.java:695)
        at org.opensearch.core.action.ActionListener$6.onFailure(ActionListener.java:311)
        at org.opensearch.telemetry.tracing.listener.TraceableActionListener.onFailure(TraceableActionListener.java:69)
        at org.opensearch.action.support.TransportAction$1.onFailure(TransportAction.java:124)
        at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.finishAsFailed(TransportReplicationAction.java:1213)
        at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:1012)
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52)
        at org.opensearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:1193)
        at org.opensearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:380)
        at org.opensearch.cluster.ClusterStateObserver$ObserverClusterStateListener.postAdded(ClusterStateObserver.java:257)
        at org.opensearch.cluster.service.ClusterApplierService$1.run(ClusterApplierService.java:346)
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:932)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedOpenSearchThreadPoolExecutor.java:283)
        at org.opensearch.common.util.concurrent.PrioritizedOpenSearchThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedOpenSearchThreadPoolExecutor.java:246)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)


```

**Comment by bigboykA** [comment]
Hi @navneet1v  I'm interested in working on this issue as my first contribution to OpenSearch k-NN. I'll start by trying to reproduce the test failure locally and investigate the root cause. Please let me know if anyone is already working on this issue or if there are any additional details I should be aware of before getting started.
