### ISSUE TITLE
[1.3.0][Distribution][BUG] k-NN build failed due to failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/k-NN#306]
```
Consolidate compiler generated dependencies of target opensearchknn_common
[ 94%] Built target opensearchknn_common
[ 97%] Building CXX object CMakeFiles/opensearchknn_nmslib.dir/src/org_opensearch_knn_jni_NmslibService.cpp.o
/tmp/tmp2q3ljrid/k-NN/jni/src/org_opensearch_knn_jni_NmslibService.cpp: In function 'jlong Java_org_opensearch_knn_jni_NmslibService_loadIndex(JNIEnv*, jclass, jstring, jobject)':
/tmp/tmp2q3ljrid/k-NN/jni/src/org_opensearch_knn_jni_NmslibService.cpp:59:12: warning: converting to non-pointer type 'long int' from NULL [-Wconversion-null]
     return NULL;
            ^
[100%] Building CXX object CMakeFiles/opensearchknn_nmslib.dir/src/nmslib_wrapper.cpp.o
[100%] Linking CXX shared library release/libopensearchknn_nmslib.so
[100%] Built target opensearchknn_nmslib
+ cd /tmp/tmp2q3ljrid/k-NN
+ ./gradlew assemble --no-daemon --refresh-dependencies -DskipTests=true -Dopensearch.version=1.3.0-SNAPSHOT -Dbuild.snapshot=true
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/tmp2q3ljrid/k-NN/build.gradle' line: 51

* What went wrong:
A problem occurred evaluating root project 'opensearch-knn'.
> Failed to apply plugin class 'org.opensearch.gradle.info.GlobalBuildInfoPlugin'.
   > Could not create plugin of type 'GlobalBuildInfoPlugin'.
      > Could not generate a decorated class for type GlobalBuildInfoPlugin.
         > org/gradle/jvm/toolchain/JavaInstallation

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 9s
2022-03-03 22:44:22 ERROR    Error building k-NN, retry with: ./build.sh manifests/1.3.0/opensearch-1.3.0.yml --component k-NN --snapshot
Traceback (most recent call last):
  File "./src/run_build.py", line 79, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 67, in main
    builder.build(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/build_workflow/builder_from_source.py", line 54, in build
    self.git_repo.execute(build_command)
  File "/var/jenkins/workspace/distribution-build-opensearch/src/git/git_repository.py", line 83, in execute
    subprocess.check_call(command, cwd=cwd, shell=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'bash /tmp/tmp2q3ljrid/k-NN/scripts/build.sh -v 1.3.0 -p linux -a x64 -s true -o builds' returned non-zero exit status 1.
```

**Comment by jmazanec15** [comment]
When did this fail? This should be fixed by https://github.com/opensearch-project/opensearch-build/pull/1704 @peterzhuamazon

**Comment by peterzhuamazon** [comment]
Got it, it failed for a while but the latest build just show as success.

```
1224
Mar 3, 2022 10:51 PM UTC
1.3.0/opensearch-1.3.0.yml
```

Thanks.
