### ISSUE TITLE
BWC Test Failure happening occassionally

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#361]
Occasionally, this failure happens in BWC test suite:
```
 org.opensearch.knn.bwc.KNNBackwardsCompatibilityIT > testBackwardsCompatibility FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at __randomizedtesting.SeedInfo.seed([DF2ECDFCB36A421C:3411F032C9B19796]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.knn.bwc.KNNBackwardsCompatibilityIT.testBackwardsCompatibility(KNNBackwardsCompatibilityIT.java:153)
REPRODUCE WITH: ./gradlew ':qa:bwc:testRollingUpgrade' --tests "org.opensearch.knn.bwc.KNNBackwardsCompatibilityIT.testBackwardsCompatibility" -Dtests.seed=DF2ECDFCB36A421C -Dtests.security.manager=false -Dtests.locale=pt-PT -Dtests.timezone=US/Eastern -Druntime.java=11
  1> [2022-04-11T12:40:19,934][INFO ][o.o.k.b.KNNBackwardsCompatibilityIT] [testBackwardsCompatibility] before test

```

For example: https://github.com/opensearch-project/k-NN/runs/5976035311?check_suite_focus=true

**Comment by jmazanec15** [comment]
Code has been refactored most likely resolving this issue. This test case no longer exists: https://github.com/opensearch-project/k-NN/tree/main/qa/rolling-upgrade/src/test/java/org/opensearch/knn/bwc.
