### ISSUE TITLE
Bumping OpenSearch Version to 3.0.0-SNAPSHOT is causing BWC Tests to fail

### ISSUE THREAD

**Issue by naveentatikonda** [opensearch-project/k-NN#465]
Rolling Upgrade BWC Tests are failing when we are trying to upgrade OpenSearch version from 2.1.0 to 3.0.0-SNAPSHOT. But, the Restart Upgrade BWC Tests are working.
The link to GitHub Action - https://github.com/naveentatikonda/k-NN/runs/7508740179?check_suite_focus=true

```
Execution failed for task ':qa:rolling-upgrade:testAgainstOneThirdUpgradedCluster'.
» WARN ][o.o.c.s.MasterService    ] [knnBwcCluster-rolling-2] failing [elected-as-cluster-manager ([2] nodes joined)[{knnBwcCluster-rolling-2}{uYRUDg_mQ62vYb7E-lOs3Q}{EW7QEd0gS76th_voQj_tIw}{127.0.0.1}{127.0.0.1:40757}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} elect leader, {knnBwcCluster-rolling-0}{nRAPlFMNTI2Yt4E4YW60RA}{WvizLTUJT7q6e49dEjcrIA}{127.0.0.1}{127.0.0.1:38491}{dimr}{testattr=test, shard_indexing_pressure_enabled=true} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_]]: failed to commit cluster state version [1]
> `cluster{:qa:rolling-upgrade:knnBwcCluster-rolling}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
    503 Service Unavailable
»  org.opensearch.cluster.coordination.FailedToCommitClusterStateException: publication failed
»  	at org.opensearch.cluster.coordination.Coordinator$CoordinatorPublication$4.onFailure(Coordinator.java:1693) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.action.ActionRunnable.onFailure(ActionRunnable.java:103) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:54) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.OpenSearchExecutors$DirectExecutorService.execute(OpenSearchExecutors.java:301) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.ListenableFuture.notifyListener(ListenableFuture.java:120) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.ListenableFuture.addListener(ListenableFuture.java:82) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Coordinator$CoordinatorPublication.onCompletion(Coordinator.java:1604) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Publication.onPossibleCompletion(Publication.java:143) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Publication.cancel(Publication.java:107) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Coordinator.cancelActivePublication(Coordinator.java:1346) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Coordinator.becomeCandidate(Coordinator.java:661) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.Coordinator.joinLeaderInTerm(Coordinator.java:560) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.cluster.coordination.JoinHelper.lambda$new$2(JoinHelper.java:191) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:103) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:453) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:798) ~[opensearch-2.1.0.jar:2.1.0]
»  	at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) ~[opensearch-2.1.0.jar:2.1.0]
»  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
»  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
»  	at java.lang.Thread.run(Thread.java:833) [?:?]
»  Caused by: org.opensearch.OpenSearchException: publication cancelled before committing: become candidate: joinLeaderInTerm
»  	at org.opensearch.cluster.coordination.Publication.cancel(Publication.java:104) ~[opensearch-2.1.0.jar:2.1.0]
»  	... 11 more
```

Security plugin also facing [same issue](https://github.com/opensearch-project/security/issues/1953). 
There is an [open issue](https://github.com/opensearch-project/OpenSearch/issues/3615) in OpenSearch. We can use this to track and check for updates.

**Comment by naveentatikonda** [comment]
Issue is fixed with this PR https://github.com/opensearch-project/k-NN/pull/498
