### ISSUE TITLE
Circuit breaker test case failure

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#734]
Since #727 , locally and in [Github actions](https://github.com/opensearch-project/k-NN/actions/runs/3960835077), we see an occassional integ test case failure:
```

> Task :integTest
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true


org.opensearch.knn.index.KNNCircuitBreakerIT > testCbUntrips FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([AC20E0A6A98FB719:10FC50C15C2FEA57]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.knn.index.KNNCircuitBreakerIT.testCbUntrips(KNNCircuitBreakerIT.java:98)
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.KNNCircuitBreakerIT.testCbUntrips" -Dtests.seed=AC20E0A6A98FB719 -Dtests.security.manager=false -Dtests.locale=de-CH -Dtests.timezone=America/Eirunepe -Druntime.java=11

Suite: Test class org.opensearch.knn.index.KNNCircuitBreakerIT
  1> [2023-01-19T18:38:05,762][INFO ][o.o.k.i.KNNCircuitBreakerIT] [testCbUntrips] before test
  1> [2023-01-19T18:38:05,764][INFO ][o.o.k.i.KNNCircuitBreakerIT] [testCbUntrips] initializing REST clients against [http://[::1]:60238, http://127.0.0.1:60239]
  1> [2023-01-19T18:40:06,792][INFO ][o.o.k.i.KNNCircuitBreakerIT] [testCbUntrips] after test
  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.KNNCircuitBreakerIT.testCbUntrips" -Dtests.seed=AC20E0A6A98FB719 -Dtests.security.manager=false -Dtests.locale=de-CH -Dtests.timezone=America/Eirunepe -Druntime.java=11
  2> java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([AC20E0A6A98FB719:10FC50C15C2FEA57]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.opensearch.knn.index.KNNCircuitBreakerIT.testCbUntrips(KNNCircuitBreakerIT.java:98)
  1> [2023-01-19T18:40:06,814][INFO ][o.o.k.i.KNNCircuitBreakerIT] [testCbTripped] before test
  1> [2023-01-19T18:40:26,617][INFO ][o.o.k.i.KNNCircuitBreakerIT] [testCbTripped] after test
  2> NOTE: leaving temporary files on disk at: /Users/jmazane/workspace/Opensearch/DockerRunner/k-NN-1/build/testrun/integTest/temp/org.opensearch.knn.index.KNNCircuitBreakerIT_AC20E0A6A98FB719-001
  2> NOTE: test params are: codec=Asserting(Lucene95): {}, docValues:{}, maxPointsInLeafNode=1388, maxMBSortInHeap=5.3591576468333715, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=de-CH, timezone=America/Eirunepe
  2> NOTE: Mac OS X 10.16 x86_64/Oracle Corporation 11.0.2 (64-bit)/cpus=12,threads=1,free=186829680,total=536870912
  2> NOTE: All tests run in this JVM: [FaissIT, KNNCircuitBreakerIT]
```

The test in question is failing to trip the circuit breaker. The result is not directly reproducible using the above command.

**Comment by navneet1v** [comment]
@jmazanec15 lets to get the full stack trace and see why it is failing. You can also try running these tests multiple time using : https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#repeats-a-given-test-n-times
