### ISSUE TITLE
[Flaky test] FaissIT.testEndToEnd_fromMethod 

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#873]
Based on https://github.com/opensearch-project/k-NN/issues/870#issuecomment-1514030956, the org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod test is flaky. 

To run:
```
./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod" -Dtests.seed=812A81B3037DB4B2 
```

logs
```
REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod" -Dtests.seed=812A81B3037DB4B2 -Dtests.security.manager=false -Dtests.locale=lv -Dtests.timezone=Asia/Novosibirsk -Druntime.java=17


Suite: Test class org.opensearch.knn.index.FaissIT


  2> apr. 19, 2023 12:29:03 AM org.opensearch.client.RestClient logResponse

  2> WARNING: request [POST http://localhost:9200/_refresh?expand_wildcards=open%2Chidden] returned 2 warnings: [299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"],[299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opensearch-knn-models], but in a future major version, direct access to system indices will be prevented by default"]

  2> REPRODUCE WITH: ./gradlew ':integTest' --tests "org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod" -Dtests.seed=812A81B3037DB4B2 -Dtests.security.manager=false -Dtests.locale=lv -Dtests.timezone=Asia/Novosibirsk -Druntime.java=17

  2> org.opensearch.client.WarningFailureException: method [POST], host [http://localhost:9200/], URI [/_refresh?expand_wildcards=open%2Chidden], status line [HTTP/1.1 200 OK]

    Warnings: [this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default, this request accesses system indices: [.opensearch-knn-models], but in a future major version, direct access to system indices will be prevented by default]

    {"_shards":{"total":7,"successful":5,"failed":0}}

        at __randomizedtesting.SeedInfo.seed([812A81B3037DB4B2:6BFAE4D879C6B949]:0)

        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:371)

        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:345)

        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)

        at app//org.opensearch.test.rest.OpenSearchRestTestCase.refreshAllIndices(OpenSearchRestTestCase.java:728)

        at app//org.opensearch.knn.index.FaissIT.testEndToEnd_fromMethod(FaissIT.java:109)

  2> NOTE: leaving temporary files on disk at: /tmp/tmp9npt3l2p/k-NN/build/testrun/integTest/temp/org.opensearch.knn.index.FaissIT_812A81B3037DB4B2-001

  2> NOTE: test params are: codec=Asserting(Lucene95): {}, docValues:{}, maxPointsInLeafNode=317, maxMBSortInHeap=6.484910423688165, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=lv, timezone=Asia/Novosibirsk

  2> NOTE: Linux 5.10.176-157.645.amzn2.aarch64 aarch64/Eclipse Adoptium 17.0.3 (64-bit)/cpus=16,threads=1,free=510601120,total=536870912

  2> NOTE: All tests run in this JVM: [FaissIT]



145 tests completed, 1 failed

```

**Comment by jmazanec15** [comment]
https://github.com/opensearch-project/k-NN/issues/874

**Comment by navneet1v** [comment]
@jmazanec15 looking at the failure what I can see is, because there are 2 warnings that has come during the test execution hence it has failed.

```
2> WARNING: request [POST http://localhost:9200/_refresh?expand_wildcards=open%2Chidden] returned 2 warnings: [299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"],[299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opensearch-knn-models], but in a future major version, direct access to system indices will be prevented by default"]
```

if we can avoid the refresh call to all the indices and just do the refresh of the index which is required, this issue should not happen.

```
http://localhost:9200/_refresh?expand_wildcards=open%2Chidden
```

**Comment by jmazanec15** [comment]
@navneet1v I am not sure if this is the root cause. I believe the tests were also failing for non-security enabled cluster as well. Taking a look into it.

**Comment by jmazanec15** [comment]
Youre right. Problem is that there are 2 warnings returned: 
```
returned 2 warnings: [299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opendistro_security], but in a future major version, direct access to system indices will be prevented by default"],[299 OpenSearch-2.7.0-fabd3f7453a0199371d78b2bb9804bfaa399306a "this request accesses system indices: [.opensearch-knn-models], but in a future major version, direct access to system indices will be prevented by default"]
```

This will cause this check to fail: https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java#L710.

However, the check after is intended to cause the request to not fail if the failure is related to system index access: https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/rest/OpenSearchRestTestCase.java#L713.

This test has same failure, but says it failed without security, which seems wrong: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/4678/pipeline. 

Agree that avoiding refresh all should resolve this. I will go ahead and make the change.

**Comment by navneet1v** [comment]
@jmazanec15 I don't think we are facing this issue as of now. Please see if we can resolve the issue.

**Comment by jmazanec15** [comment]
@navneet1v Why? I dont think a conclusion has been reached yet

**Comment by navneet1v** [comment]
@jmazanec15 can you please add details what is left from this issue?

**Comment by jmazanec15** [comment]
Sure, it looks like we need to root cause the test failure. Im not sure if avoiding refresh is correct solution. @heemin32 or @VijayanB can either of you pick this up?

**Comment by jmazanec15** [comment]
This is completed with #1365
