### ISSUE TITLE
[Flaky test] org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.testTrainingDeletedModel

### ISSUE THREAD

**Issue by jmazanec15** [opensearch-project/k-NN#888]
Refer to: https://github.com/opensearch-project/k-NN/actions/runs/4875989257/jobs/8698908112

```
REPRODUCE WITH: gradlew ':integTest' --tests "org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.testTrainingDeletedModel" -Dtests.seed=855A1546DEBE5A24 -Dtests.security.manager=false -Dtests.locale=en-MT -Dtests.timezone=Etc/GMT-13 -Druntime.java=17
org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT > testTrainingDeletedModel FAILED

    org.opensearch.client.ResponseException: method [POST], host [http://[::1]:50139], URI [/_plugins/_knn/models/test-model-id1/_train], status line [HTTP/1.1 400 Bad Request]

    {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: Model with id=\"test-model-id1\" already exists;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: Model with id=\"test-model-id1\" already exists;"},"status":400}
Suite: Test class org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT
        at __randomizedtesting.SeedInfo.seed([855A1546DEBE5A24:65D988AD3DF2DEF5]:0)
  2> REPRODUCE WITH: gradlew ':integTest' --tests "org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.testTrainingDeletedModel" -Dtests.seed=855A1546DEBE5A24 -Dtests.security.manager=false -Dtests.locale=en-MT -Dtests.timezone=Etc/GMT-13 -Druntime.java=17
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
  2> org.opensearch.client.ResponseException: method [POST], host [http://[::1]:50139], URI [/_plugins/_knn/models/test-model-id1/_train], status line [HTTP/1.1 400 Bad Request]
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:345)
    {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: Model with id=\"test-model-id1\" already exists;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: Model with id=\"test-model-id1\" already exists;"},"status":400}
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at __randomizedtesting.SeedInfo.seed([855A1546DEBE5A24:65D988AD3DF2DEF5]:0)
        at app//org.opensearch.knn.KNNRestTestCase.trainModel(KNNRestTestCase.java:1099)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:375)
        at app//org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.trainModel(RestDeleteModelHandlerIT.java:199)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:345)
        at app//org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.testTrainingDeletedModel(RestDeleteModelHandlerIT.java:147)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
  1> [2023-05-04T09:12:51,314][INFO ][o.o.k.p.a.RestDeleteModelHandlerIT] [testDeleteTrainingModel] before test
        at app//org.opensearch.knn.KNNRestTestCase.trainModel(KNNRestTestCase.java:1099)
  1> [2023-05-04T09:12:51,317][INFO ][o.o.k.p.a.RestDeleteModelHandlerIT] [testDeleteTrainingModel] initializing REST clients against [http://127.0.0.1:50138/, http://[::1]:50139]
        at app//org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.trainModel(RestDeleteModelHandlerIT.java:199)
        at app//org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT.testTrainingDeletedModel(RestDeleteModelHandlerIT.java:147)
  2> NOTE: leaving temporary files on disk at: D:\a\k-NN\k-NN\build\testrun\integTest\temp\org.opensearch.knn.plugin.action.RestDeleteModelHandlerIT_855A1546DEBE5A24-001
```

**Comment by navneet1v** [comment]
@jmazanec15 can we resolve this issue ? I don't think so we are facing similar issues again

**Comment by jmazanec15** [comment]
Yes I think so - we are removing test in https://github.com/opensearch-project/k-NN/pull/1423 and most likely happened due to some failure with cleaning up models.
